name: DeployFiles

on:
  push:
    tag:
      - 'v*'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Package Both
        run: |
          tar -czvf numeric_any_${{ github.ref_name }}.tar.gz src/ README.md CMakeLists.txt LICENSE.txt
          zip -r numeric_any_${{ github.ref_name }}.zip src/ README.md CMakeLists.txt LICENSE.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            *.tar.gz
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          