name: TestingComplie

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-26.04, windows-latest]
        build_type: [Debug, Release]
        codes: ["tests/units", "tests/benchmarks"]
        generator_code: ["-G Ninja", ""]
        cpp_compiler: [g++-15, clang++, cl]
        cpp_standard: [20, 23]
        include:
          - os: windows-latest
            cpp_compiler: cl
          - os: windows-latest
            cpp_compiler: clang++
          - os: windows-latest
            generator_code: ""
          - os: ubuntu-26.04
            cpp_compiler: g++-15
          - os: ubuntu-26.04
            cpp_compiler: clang++
          - os: ubuntu-26.04
            generator_code: "-G Ninja"
          - codes: "tests/units"
            build_type: Debug
          - codes: "tests/benchmarks"
            build_type: Release
        exclude:
          - os: windows-latest
            cpp_compiler: g++-15
          - os: windows-latest
            generator_code: "-G Ninja"
          - os: ubuntu-26.04
            cpp_compiler: cl
          - os: ubuntu-26.04
            generator_code: ""
          - codes: "tests/benchmarks"
            build_type: Debug
          - codes: "tests/units"
            build_type: Release
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B ${{ matrix.codes }}/build
        ${{ matrix.generator_code }}
        -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ matrix.codes }}

    - name: Build
      run: cmake --build ${{ matrix.codes }}/build --config ${{ matrix.build_type }}