name: TestingComplie

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        build_to: ["tests/units/build", "tests/benchmarks/build"]
        codes: ["tests/units", "tests/benchmarks"]
        cpp_compiler: [g++, clang++, cl]
        cpp_standard: [20, 23]
        include:
          - os: windows-latest
            cpp_compiler: cl
          - os: windows-latest
            cpp_compiler: clang++
          - os: ubuntu-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B ${{ matrix.build_to }}
        -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ matrix.codes }}

    - name: Build
      run: cmake --build ${{ matrix.build_to }} --config ${{ matrix.build_type }}