name: ExamplesTests

on:
  push:
    paths:
      - 'src/**'
      - 'examples/**'
  pull_request:
    paths:
      - 'src/**'
      - 'examples/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-26.04, windows-latest]
        generator_code: ["-G Ninja", ""]
        cpp_compiler: [g++-15, clang++, cl]
        include:
          - os: windows-latest
            cpp_compiler: cl
          - os: windows-latest
            cpp_compiler: clang++
          - os: windows-latest
            generator_code: ""
          - os: ubuntu-26.04
            cpp_compiler: g++-15
          - os: ubuntu-26.04
            cpp_compiler: clang++
          - os: ubuntu-26.04
            generator_code: "-G Ninja"
        exclude:
          - os: windows-latest
            cpp_compiler: g++-15
          - os: windows-latest
            generator_code: "-G Ninja"
          - os: ubuntu-26.04
            cpp_compiler: cl
          - os: ubuntu-26.04
            generator_code: ""
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake -B examples/build
        ${{ matrix.generator_code }}
        -DCMAKE_CXX_STANDARD=23
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        -S examples

    - name: Build
      run: cmake --build examples/build --config Release
    